### ISSUE TITLE
Growl po włączeniu aplikacji

### ISSUE THREAD

**Issue by filiptepper** [mackuba/MacBlip#1]
IMHO po włączeniu aplikacji wiadomości nie powinny być growlowane.

Może niech MacBlip załaduje wszystkie wiadomości, a dopiero przy odświeżaniu korzysta z Growla?

**Comment by marcin-maciukiewicz** [comment]
Zgadzam sie. Odpalilem MacBlipa i zasypal mnie powiadomieniami.

**Comment by mackuba** [comment]
Zrobiłem tak, że jeśli jest więcej niż 5, to reszta się grupuje - może być? W każdym razie problemu z zasypywaniem już nie będzie.
