### ISSUE TITLE
Brak/zbyt duży timeout przy logowaniu

### ISSUE THREAD

**Issue by grzegor** [mackuba/MacBlip#2]
Po pierwszym uruchomieniu rozbił mi się o firewalla, czego nie zauważyłem (a nawet wydaje mi się, że z jakiegoś powodu LittleSnitch nie wyświetlił monitu) no i się logował aż do ręcznego force kill'a.

**Comment by mackuba** [comment]
Czyli mówisz że logował się tak uparcie że aż się zwiesił? Hmm... teoretycznie jest to tak zrobione, że powinien odczekać 10 sekund i spróbować jeszcze raz, chyba że coś przegapiłem.

Sprawdź czy za drugim razem to samo zrobi, a jeśli tak, to włącz mu logowanie w ten sposób:

```
defaults write net.psionides.MacBlip 'objectiveblip.forceLogging' -bool YES
```

i włącz sobie konsolę (w sensie Console), odpal jeszcze raz, i zobacz co ci tam leci (tylko ostrożnie bo w tej sytuacji to może lecieć sporo tego...) i wklej mi kawałek.
